# Generated by Django 3.2.23 on 2024-02-28 23:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0003_customuser_date_of_birth'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shippingaddress',
            options={'verbose_name_plural': 'Shipping Addresses'},
        ),
    ]
