# Generated by Django 4.1.2 on 2024-03-26 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0003_alter_ticket_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="ticket",
            name="viewed",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="ticketmessages",
            name="viewed",
            field=models.BooleanField(default=False),
        ),
    ]
