# Generated by Django 4.1.2 on 2024-03-26 21:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0004_ticket_viewed_ticketmessages_viewed"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ticket",
            name="viewed",
        ),
        migrations.RemoveField(
            model_name="ticketmessages",
            name="viewed",
        ),
    ]
