# Generated by Django 5.1.6 on 2025-03-18 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0005_remove_ticket_viewed_remove_ticketmessages_viewed"),
    ]

    operations = [
        migrations.AddField(
            model_name="ticketmessages",
            name="is_read",
            field=models.BooleanField(default=False),
        ),
    ]
