# Generated by Django 3.2.23 on 2024-03-05 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0007_alter_order_discount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='order',
            name='last_name',
        ),
        migrations.AddField(
            model_name='order',
            name='full_name',
            field=models.CharField(default='name', editable=False, max_length=64),
            preserve_default=False,
        ),
    ]
