# Generated by Django 3.2.23 on 2024-01-05 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HomePage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('jumbotron_text', models.TextField()),
                ('jumbotron_image', models.ImageField(upload_to='jumbotron_images/')),
            ],
        ),
    ]
