# Generated by Django 3.2.23 on 2024-02-07 23:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HomePage',
        ),
    ]
