# Generated by Django 5.1.6 on 2025-02-21 12:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0001_initial"),
        ("products", "0003_alter_product_discounted_price_alter_product_price"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="herosection",
            name="product",
        ),
        migrations.AddField(
            model_name="herosection",
            name="category",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="products.category",
            ),
        ),
    ]
