# Generated by Django 5.1.6 on 2025-02-25 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0002_remove_herosection_product_herosection_category"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="herosection",
            name="category",
        ),
        migrations.AddField(
            model_name="herosection",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="hero_section"),
        ),
        migrations.AddField(
            model_name="herosection",
            name="link",
            field=models.URLField(default="#"),
        ),
        migrations.AddField(
            model_name="herosection",
            name="link_text",
            field=models.CharField(default="Shop Now", max_length=50),
        ),
        migrations.AddField(
            model_name="herosection",
            name="subtitle",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="herosection",
            name="title",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
