# Generated by Django 5.1.6 on 2025-03-16 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0003_remove_herosection_category_herosection_image_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="herosection",
            name="intro_header",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="herosection",
            name="intro_text",
            field=models.TextField(blank=True, null=True),
        ),
    ]
