# Generated by Django 5.1.6 on 2025-03-16 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0004_herosection_intro_header_herosection_intro_text"),
    ]

    operations = [
        migrations.AddField(
            model_name="herosection",
            name="intro_image",
            field=models.ImageField(blank=True, null=True, upload_to="hero_section"),
        ),
    ]
