# Generated by Django 3.2.23 on 2024-01-05 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20240105_0554'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='discount',
            new_name='discounted_price',
        ),
    ]
