# Generated by Django 3.2.23 on 2024-01-05 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_rename_discount_product_discounted_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='discount_percentage',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
    ]
