# Generated by Django 5.1.6 on 2025-02-25 23:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0004_producttype_remove_product_image_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductVariant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(blank=True, null=True, upload_to="")),
                (
                    "variant_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("flavor", "Flavor"),
                            ("nicotine", "Nicotine Strength"),
                            ("size", "Size"),
                            ("color", "Color"),
                        ],
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "sku",
                    models.CharField(
                        blank=True, max_length=254, null=True, unique=True
                    ),
                ),
                ("countInStock", models.IntegerField(blank=True, default=0, null=True)),
                ("additional_info", models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name="productvariation",
            name="multi_options",
        ),
        migrations.RemoveField(
            model_name="productimage",
            name="product",
        ),
        migrations.DeleteModel(
            name="ProductType",
        ),
        migrations.RemoveField(
            model_name="productvariation",
            name="product",
        ),
        migrations.RemoveField(
            model_name="brand",
            name="description",
        ),
        migrations.RemoveField(
            model_name="product",
            name="countInStock",
        ),
        migrations.RemoveField(
            model_name="product",
            name="discount_percentage",
        ),
        migrations.RemoveField(
            model_name="product",
            name="free_shipping",
        ),
        migrations.RemoveField(
            model_name="product",
            name="sku",
        ),
        migrations.AddField(
            model_name="category",
            name="category_image",
            field=models.ImageField(blank=True, upload_to="categories"),
        ),
        migrations.AddField(
            model_name="category",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="children",
                to="products.category",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="rating",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=6, null=True
            ),
        ),
        migrations.AddField(
            model_name="productvariant",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="variants",
                to="products.product",
            ),
        ),
        migrations.DeleteModel(
            name="MultiOption",
        ),
        migrations.DeleteModel(
            name="ProductImage",
        ),
        migrations.DeleteModel(
            name="ProductVariation",
        ),
    ]
