# Generated by Django 3.2.23 on 2024-01-05 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_review'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='createdAt',
            new_name='created_at',
        ),
    ]
