# Generated by Django 5.1.6 on 2025-03-17 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0007_product_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="countInStock",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name="product",
            name="sku",
            field=models.CharField(blank=True, max_length=254, null=True, unique=True),
        ),
    ]
