# Generated by Django 3.2.23 on 2024-01-05 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_product_multi_choice'),
    ]

    operations = [
        migrations.CreateModel(
            name='MultiChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.RemoveField(
            model_name='product',
            name='multi_choice',
        ),
        migrations.AddField(
            model_name='product',
            name='choices',
            field=models.ManyToManyField(blank=True, null=True, to='products.MultiChoice'),
        ),
    ]
