# Generated by Django 5.1.6 on 2025-03-17 21:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0008_product_countinstock_product_sku"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="countInStock",
        ),
        migrations.RemoveField(
            model_name="product",
            name="image",
        ),
        migrations.RemoveField(
            model_name="product",
            name="sku",
        ),
    ]
