# Generated by Django 3.2.23 on 2024-01-05 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_auto_20240105_1726'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='choices',
        ),
        migrations.AddField(
            model_name='product',
            name='choices',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
