# Generated by Django 3.2.23 on 2024-01-08 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_auto_20240105_2040'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='num_reviews',
        ),
    ]
