# Generated by Django 3.2.23 on 2024-01-10 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_auto_20240110_1608'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='multioption',
            name='option_name',
        ),
    ]
