# Generated by Django 3.2.23 on 2024-01-17 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0016_remove_product_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='multioption',
            name='options',
        ),
        migrations.RemoveField(
            model_name='product',
            name='option',
        ),
        migrations.AddField(
            model_name='multioption',
            name='name',
            field=models.CharField(default='', max_length=254),
        ),
        migrations.AddField(
            model_name='product',
            name='options',
            field=models.ManyToManyField(blank=True, null=True, to='products.MultiOption'),
        ),
    ]
