# Generated by Django 3.2.23 on 2024-01-30 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0020_auto_20240130_1600'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brand',
            name='friendly_name',
        ),
        migrations.RemoveField(
            model_name='category',
            name='friendly_name',
        ),
    ]
